#!/bin/ksh

function bd {
    if [ ! -z "$libreriaDesdeScript" ]; then
        ruta="./../BaseDeDatos"
    else
        ruta="./BaseDeDatos"
    fi
    respuesta="$(
        cd "$ruta"
        ./databaseManager.ksh $*
    )"
    if(( "$?" != 0 ));then
        print "$respuesta" 
        exit 1
    fi

    print "$respuesta"
}
