#!/bin/ksh

function bd {
    respuesta="$(
        cd ./BaseDeDatos
        ./databaseManager.ksh $*
    )"
    if(( "$?" != 0 ));then

        print "$respuesta" 
        exit 1
    fi

    print "$respuesta"
}
