#!/bin/ksh

# Recibe un color (predefinido en la función) y lo setea para el texto.
# Si recibe "reset" reinicia los colores al default.
# Si no está y lo quieren pónganlo.
# https://linux.101hacks.com/ps1-examples/prompt-color-using-tput/

function easyTput {
    opcion="$1"
    case "$opcion" in
    reset*) tput sgr0;;
    colortexto*) tput setaf `color $2`;;
    colorfondo*) tput setab `color $2`;;
    negrita*) tput bold ;;
    debil*) tput dim;;
    subrayado*) tput smul;;
    nosubrayado*) tput rmul;;
    *) print "Opción no definida" ;;
    esac
}

function color {
    color="$1"
    case "$color" in
    negro) print "0" ;;
    rojo) print "1" ;;
    verde) print "2" ;;
    amarillo) print "3" ;;
    azul) print "4" ;;
    magenta) print "5" ;;
    cyan) print "6" ;;
    blanco) print "7" ;;
    esac
}
